### ISSUE TITLE
can't load local test data

### ISSUE THREAD

**Issue by devincowan** [podaac/hydrocron#81]
Perhaps introduced in https://github.com/podaac/hydrocron/pull/26, when I attempt to `poetry run python tests/load_data_local.py` I get the following:
```
Traceback (most recent call last):
  File "/Users/dcowan/repos/hydrocron/tests/load_data_local.py", line 16, in <module>
    hydrocron.db.load_data.load_data(
  File "/Users/dcowan/repos/hydrocron/hydrocron/db/load_data.py", line 213, in load_data
    hydrocron_table = HydrocronTable(dyn_resource=dynamo_resource, table_name=table_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dcowan/repos/hydrocron/hydrocron/db/schema.py", line 29, in __init__
    if self.exists(table_name):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dcowan/repos/hydrocron/hydrocron/db/schema.py", line 55, in exists
    table = self.dyn_resource.Table(table_name)
            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HydrocronTable' object has no attribute 'Table'. Did you mean: 'table'?
```
And it does look like the first arg passed into `hydrocron.db.load_data.load_data()` [here](https://github.com/podaac/hydrocron/blob/release/1.0.0/tests/load_data_local.py#L17) should be a dynamo_instance, not a `HydrocronTable` instance.

Run using ed090b7aa71d047409acf681f586cc99306f6fdc (tag [1.0.0rc2](https://github.com/podaac/hydrocron/releases/tag/1.0.0rc2))

Same result after checking out current `develop` branch at 1a9e2e493157453975f56937d35b7782b4e50d91

**Comment by devincowan** [comment]
if I revert to [1.0.0a14](https://github.com/podaac/hydrocron/releases/tag/1.0.0a14) and `poetry run python tests/load_data_local.py` then everything loads just dandy.
